# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    
    resolvers:
        default:
            web_path: ~
    
    filter_sets:
        lot_thumbnail:
            filters:
                thumbnail:
                    size:          [40, 40]
                    mode:          outbound
                    allow_upscale: true
                    
        user_thumbnail:
            filters:
                thumbnail:
                    size:          [40, 40]
                    mode:          outbound
                    allow_upscale: true
